#!/usr/bin/env python3
'''
Given a "MOSS linkage" JSON (e.g. generated by moss_connectivity.py), output a TSV of (email1, email2, num_links)
Niema Moshiri 2019
'''
from mossnet import build

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('-i', '--input', required=False, type=str, default='stdin', help="MOSS URLs (one-per-line)")
    parser.add_argument('-o', '--output', required=True, type=str, help="Output MossNet File (pkl)")
    args = parser.parse_args()
    if args.input == 'stdin':
        from sys import stdin as infile
    else:
        infile = open(args.input)
    urls = [l.strip() for l in infile if len(l.strip()) != 0]
    mn = build(urls, verbose=True)
    mn.save(args.output)
